# Taller de Tensores
---


In [3]:
import tensorflow as tf
import numpy as np
import os


In [ ]:
print(f'tensorflow: {tf.__version__}')
print(f'numpy: {np.__version__}')

tensorflow: 2.4.1
numpy: 1.19.5


Este notebook se realizó con las versiones:
> tensorflow: 2.4.1

> numpy: 1.19.5



### Tensor de Adios
---
Cargamos el tensor de audios de cetáceos

In [ ]:
#si esta trabajando en google drive
from google.colab import drive
drive.mount('/content/drive')

pathdir = '/content/drive/MyDrive/Colab Notebooks/IA y AP/Proyecto/Audios/'
listdir = os.listdir(pathdir)
print(f'Cantidad de audios: {len(listdir)}')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Cantidad de audios: 1697


In [ ]:
#cargamos el tensor de audios
path = '/content/drive/MyDrive/Colab Notebooks/IA y AP/Proyecto/' #Trabajando desde Drive
#path = '/home/mofoko/Desktop/Diplomato intel artificial/IA y AP/Proyecto/' #Trabajando desde local
npz = np.load(path + 'Tensor_ceatceos.npz')

In [ ]:
print(type(npz))
#npz guarda el tensor en un diccionario
print(npz.files) #.files nos da las keys del diccionario
T = np.array(npz['arr_0'])
print(T)
print(T.shape)

<class 'numpy.lib.npyio.NpzFile'>
['arr_0']
[[[ 4.49563786e-02  0.00000000e+00]
  [ 6.17534816e-02  4.53514739e-05]
  [ 5.63177690e-02  9.07029478e-05]
  ...
  [ 1.72668621e-02  4.97129252e+00]
  [ 2.19469201e-02  4.97133787e+00]
  [ 7.48272240e-03  4.97138322e+00]]

 [[ 3.68937780e-03  0.00000000e+00]
  [ 1.20888213e-02  1.56908156e-04]
  [ 1.37021476e-02  3.13816313e-04]
  ...
  [-2.36057267e-02  1.71998014e+01]
  [-2.23530717e-02  1.71999583e+01]
  [ 0.00000000e+00  1.72001152e+01]]

 [[ 2.89834309e-02  0.00000000e+00]
  [ 4.94505689e-02  1.40939986e-04]
  [ 4.60001454e-02  2.81879972e-04]
  ...
  [ 8.60219747e-02  1.54494184e+01]
  [ 9.03071985e-02  1.54495594e+01]
  [ 7.36405477e-02  1.54497003e+01]]

 ...

 [[-1.81061495e-02  0.00000000e+00]
  [-2.60394644e-02  1.18623354e-04]
  [-2.38069836e-02  2.37246708e-04]
  ...
  [ 2.12385189e-02  1.30031362e+01]
  [ 2.87449583e-02  1.30032548e+01]
  [ 3.03709973e-02  1.30033734e+01]]

 [[-1.07235275e-01  0.00000000e+00]
  [-2.02339560e-01

In [ ]:
print(f'Primero audio: {T[0, :, :].shape}')

Primero audio: (109620, 2)


## Rango Tensores
---

Definir números, vectores y matrices en **tf** como tensores de rango cero, uno y dos.

In [ ]:
#definir una constante o tenor de rango cero
num = np.around(T[0, 0, 0], 4)
t0 = tf.constant(num)
print(t0)

tf.Tensor(0.045, shape=(), dtype=float64)


In [ ]:
#definir un vector o tensor de rango 1
v = np.around(T[0, 0:3, 0], 4)
t1 = tf.constant(v)
print(t1)

tf.Tensor([0.045  0.0618 0.0563], shape=(3,), dtype=float64)


In [ ]:
#definir una matriz o tensor de rango 2
M = np.around(T[0, 0:3, 0:3], 4)
t2 = tf.constant(M)
print(t2)

tf.Tensor(
[[0.045  0.    ]
 [0.0618 0.    ]
 [0.0563 0.0001]], shape=(3, 2), dtype=float64)


In [ ]:
#definir un tensor de rango 3
tensor = np.around(T[0:2, 0:3, 0:3], 4)
t3 = tf.constant(tensor)
print(t3)

tf.Tensor(
[[[0.045  0.    ]
  [0.0618 0.    ]
  [0.0563 0.0001]]

 [[0.0037 0.    ]
  [0.0121 0.0002]
  [0.0137 0.0003]]], shape=(2, 3, 2), dtype=float64)


In [ ]:
#converitir un tensor de tensorflow a un arreglo numpy
t3.numpy()

array([[[0.045 , 0.    ],
        [0.0618, 0.    ],
        [0.0563, 0.0001]],

       [[0.0037, 0.    ],
        [0.0121, 0.0002],
        [0.0137, 0.0003]]])

In [ ]:
#tensor (array) de numpy
t3.numpy().shape

(2, 3, 2)

In [ ]:
#tensor de tensorflow
t3.shape

TensorShape([2, 3, 2])

## Algebra mínima de tensores
---

In [ ]:
#definimos dos matrices
a = tf.constant(np.around(T[0, 0:2, 0:2], 4))
b = tf.constant(np.around(T[1, 0:2, 0:2], 4))

#las sumamos, multiplicamos
print('Matriz a:')
print(a,"\n")
print('Matriz b:')
print(b,"\n")
print('Matriz a+b:')
print(tf.add(a,b),"\n") #suma matricial
print('Matriz a(*)b:')
print(tf.multiply(a,b),"\n") #Hadamard product
print('Matriz a*b:')
print(tf.matmul(a,b),"\n") #multiplicacion de matrices

Matriz a:
tf.Tensor(
[[0.045  0.    ]
 [0.0618 0.    ]], shape=(2, 2), dtype=float64) 

Matriz b:
tf.Tensor(
[[0.0037 0.    ]
 [0.0121 0.0002]], shape=(2, 2), dtype=float64) 

Matriz a+b:
tf.Tensor(
[[0.0487 0.    ]
 [0.0739 0.0002]], shape=(2, 2), dtype=float64) 

Matriz a(*)b:
tf.Tensor(
[[0.0001665  0.        ]
 [0.00074778 0.        ]], shape=(2, 2), dtype=float64) 

Matriz a*b:
tf.Tensor(
[[0.0001665  0.        ]
 [0.00022866 0.        ]], shape=(2, 2), dtype=float64) 



In [ ]:
#las operaciones anteriores tambien se pueden hacer asi
print(a+b,"\n") #suma de matrices
print(a*b, "\n") #Hadamard product
print(a@b, "\n") #multiplicacion de matrices

tf.Tensor(
[[0.0487 0.    ]
 [0.0739 0.0002]], shape=(2, 2), dtype=float64) 

tf.Tensor(
[[0.0001665  0.        ]
 [0.00074778 0.        ]], shape=(2, 2), dtype=float64) 

tf.Tensor(
[[0.0001665  0.        ]
 [0.00022866 0.        ]], shape=(2, 2), dtype=float64) 



## Funciones de Reducción¶
---

In [ ]:
c = tf.constant(T[2, 0:3, 0:2])

print('Matriz c:')
print(c,"\n")
print('máximo valor de Matriz c:')
print(tf.reduce_max(c),"\n") #maximo valos en la matriz
print('mínimo valor de Matriz c:')
print(tf.reduce_min(c),"\n") #minimo valor de la matriz
print('media aritmética de Matriz c:')
print(tf.reduce_mean(c),"\n") #media aritmeticas de los valores de la matriz
print('idx de los máximos valores de Matriz c en cada columna:')
print(tf.argmax(c, axis=None),"\n") #devulve los indices en un eje del mayor valor de la matriz o menor en caso de empates
print('softmax de Matriz c:')
print(tf.nn.softmax(c),"\n") #aplica la funcion de activacion softmax a la matriz
print('suma de los vectores columna de softmax de Matriz c:')
print(tf.reduce_sum(tf.nn.softmax(c),axis=1),"\n") #suma todos los elementos de la matriz en el eje 1 es decir las columnas
# es decir [0.50724535, 0.51232491. 0.51142758] + [0.49275465, 0.48767509, 0.48857242] = [1.0, 1.0, 1.0]

Matriz c:
tf.Tensor(
[[0.02898343 0.        ]
 [0.04945057 0.00014094]
 [0.04600015 0.00028188]], shape=(3, 2), dtype=float64) 

máximo valor de Matriz c:
tf.Tensor(0.04945056885480881, shape=(), dtype=float64) 

mínimo valor de Matriz c:
tf.Tensor(0.0, shape=(), dtype=float64) 

media aritmética de Matriz c:
tf.Tensor(0.02080949418759895, shape=(), dtype=float64) 

idx de los máximos valores de Matriz c en cada columna:
tf.Tensor([1 2], shape=(2,), dtype=int64) 

softmax de Matriz c:
tf.Tensor(
[[0.50724535 0.49275465]
 [0.51232491 0.48767509]
 [0.51142758 0.48857242]], shape=(3, 2), dtype=float64) 

suma de los vectores columna de softmax de Matriz c:
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float64) 



## Indexación
---
+ Los índices empiezam em cero.
+ Los índices negativos cuentan hacia atrás desde el final.
+ Los dos puntos (:) se utilizan para los cortes. inicio:final:salto

In [ ]:
t1 =  tf.constant(np.around(T[0, 0:5, 0], 4))
print('vector:', t1)
print("Primero: ", t1[0])
print("Segundo: ", t1[1])
print("Ultimo: ", t1[-1].numpy())

vector: tf.Tensor([0.045  0.0618 0.0563 0.0624 0.0583], shape=(5,), dtype=float64)
Primero:  tf.Tensor(0.045, shape=(), dtype=float64)
Segundo:  tf.Tensor(0.0618, shape=(), dtype=float64)
Ultimo:  0.0583


### Extracción de partes de un tensor: *slices*

In [ ]:
t1 =  tf.constant(np.around(T[0, :10, 0], 4))
print('Todo', t1[:].numpy()) 
print('Antes la posición 4 ', t1[:4].numpy()) #los elementos con indices 0, 1, 2, 3 sin incluir el 4
print('Desde la posición 4 hasta el final', t1[4:].numpy()) #todos los elementos despues del cuarto elemento
print('Desde la posición 2 hasta anterior a 7', t1[4:7].numpy()) #elementos con indices 4, 5, 6 sin incluir el idx 7
print('Todos los elementos en posición par ', t1[::2].numpy()) #los elemento con idx pares 0, 2, 4, 6 ...
print('Invertido todo el orden', t1[::-1].numpy()) #todos los elemmentos en orden inverso


Todo [0.045  0.0618 0.0563 0.0624 0.0583 0.0591 0.0559 0.0593 0.0561 0.0584]
Antes la posición 4  [0.045  0.0618 0.0563 0.0624]
Desde la posición 4 hasta el final [0.0583 0.0591 0.0559 0.0593 0.0561 0.0584]
Desde la posición 2 hasta anterior a 7 [0.0583 0.0591 0.0559]
Todos los elementos en posición par  [0.045  0.0563 0.0583 0.0559 0.0561]
Invertido todo el orden [0.0584 0.0561 0.0593 0.0559 0.0591 0.0583 0.0624 0.0563 0.0618 0.045 ]


## Indexación multi-eje

In [ ]:
m = np.transpose(np.around(T[0, :3, :], 4))
t23 = tf.constant(m)
print(t23.numpy())

[[0.045  0.0618 0.0563]
 [0.     0.     0.0001]]


In [ ]:
print('Posición 1,1 = ',t23[1,1].numpy())
print('Segunda fila: ', t23[1,:].numpy())
print('Segunda columna: ', t23[:,1].numpy())
print('Última columna: ', t23[:,-1].numpy())
print('Primer elemento de la última columna: ', t23[0,-1].numpy())
print('Saltarse la primera columna: \n', t23[:,1:].numpy())


Posición 1,1 =  0.0
Segunda fila:  [0.     0.     0.0001]
Segunda columna:  [0.0618 0.    ]
Última columna:  [0.0563 0.0001]
Primer elemento de la última columna:  0.0563
Saltarse la primera columna: 
 [[0.0618 0.0563]
 [0.     0.0001]]


In [ ]:
m = np.around(T[:3, :5, :], 4)
t = tf.constant(m) 
print(t.numpy())

[[[0.045  0.    ]
  [0.0618 0.    ]
  [0.0563 0.0001]
  [0.0624 0.0001]
  [0.0583 0.0002]]

 [[0.0037 0.    ]
  [0.0121 0.0002]
  [0.0137 0.0003]
  [0.0212 0.0005]
  [0.0283 0.0006]]

 [[0.029  0.    ]
  [0.0495 0.0001]
  [0.046  0.0003]
  [0.0479 0.0004]
  [0.0419 0.0006]]]


In [ ]:
print('Extrae la primera capa\n', t[0,:,:])
print('Extrae la segunda capa\n', t[1])

Extrae la primera capa
 tf.Tensor(
[[0.045  0.    ]
 [0.0618 0.    ]
 [0.0563 0.0001]
 [0.0624 0.0001]
 [0.0583 0.0002]], shape=(5, 2), dtype=float64)
Extrae la segunda capa
 tf.Tensor(
[[0.0037 0.    ]
 [0.0121 0.0002]
 [0.0137 0.0003]
 [0.0212 0.0005]
 [0.0283 0.0006]], shape=(5, 2), dtype=float64)


## Manipular formas


In [ ]:
x = tf.constant(np.around(T[:3, :1, 0], 4))
print(x.shape)
print(x.shape.as_list())

(3, 1)
[3, 1]


In [ ]:
reshaped = tf.reshape(x,[1,3])
print(reshaped.numpy())
print(x.numpy())

[[0.045  0.0037 0.029 ]]
[[0.045 ]
 [0.0037]
 [0.029 ]]


Con ```tf.reshape``` los datos mantienen su disposición en la memoria y se crea un nuevo tensor, con la forma solicitada, apuntando a los mismos datos. TensorFlow usa un orden de memoria de "fila principal" de estilo C, donde incrementar el índice de la derecha corresponde a un solo paso en la memoria.

## Aplana un tensor
---
Esta operación permite ver el orden como están organizados los datos en memoria

In [ ]:
print("t actual: \n", t.numpy())
flat = tf.reshape(t, [-1])
print("\n t aplanado: \n", flat.numpy())

t actual: 
 [[[0.045  0.    ]
  [0.0618 0.    ]
  [0.0563 0.0001]
  [0.0624 0.0001]
  [0.0583 0.0002]]

 [[0.0037 0.    ]
  [0.0121 0.0002]
  [0.0137 0.0003]
  [0.0212 0.0005]
  [0.0283 0.0006]]

 [[0.029  0.    ]
  [0.0495 0.0001]
  [0.046  0.0003]
  [0.0479 0.0004]
  [0.0419 0.0006]]]

 t aplanado: 
 [0.045  0.     0.0618 0.     0.0563 0.0001 0.0624 0.0001 0.0583 0.0002
 0.0037 0.     0.0121 0.0002 0.0137 0.0003 0.0212 0.0005 0.0283 0.0006
 0.029  0.     0.0495 0.0001 0.046  0.0003 0.0479 0.0004 0.0419 0.0006]


Normalmente, el único uso razonable de tf.reshape es combinar o dividir ejes adyacentes (o agregar / eliminar 1 s).

Para este tensor de 2x3x5, remodelar a (2x3)x5 o 2x (3x5) son dos cosas razonables, ya que los cortes no se mezclan:

In [ ]:
print(t.shape.as_list())

[3, 5, 2]


In [ ]:
print(tf.reshape(t, [2*3,5]))

tf.Tensor(
[[0.045  0.     0.0618 0.     0.0563]
 [0.0001 0.0624 0.0001 0.0583 0.0002]
 [0.0037 0.     0.0121 0.0002 0.0137]
 [0.0003 0.0212 0.0005 0.0283 0.0006]
 [0.029  0.     0.0495 0.0001 0.046 ]
 [0.0003 0.0479 0.0004 0.0419 0.0006]], shape=(6, 5), dtype=float64)


In [ ]:
print(tf.reshape(t, [2,3*5]))

tf.Tensor(
[[0.045  0.     0.0618 0.     0.0563 0.0001 0.0624 0.0001 0.0583 0.0002
  0.0037 0.     0.0121 0.0002 0.0137]
 [0.0003 0.0212 0.0005 0.0283 0.0006 0.029  0.     0.0495 0.0001 0.046
  0.0003 0.0479 0.0004 0.0419 0.0006]], shape=(2, 15), dtype=float64)


No es necesario definir todos los tamaños en todas las dimensiones. veámos como rehacer los dos ejemplos anteriores, respecitivamente. El **-1** le dice a tf que **decida cuál es la dimensión correcta**.

In [ ]:
print(tf.reshape(t, [-1,5]))

tf.Tensor(
[[0.045  0.     0.0618 0.     0.0563]
 [0.0001 0.0624 0.0001 0.0583 0.0002]
 [0.0037 0.     0.0121 0.0002 0.0137]
 [0.0003 0.0212 0.0005 0.0283 0.0006]
 [0.029  0.     0.0495 0.0001 0.046 ]
 [0.0003 0.0479 0.0004 0.0419 0.0006]], shape=(6, 5), dtype=float64)


In [ ]:
print(tf.reshape(t, [3,-1]))

tf.Tensor(
[[0.045  0.     0.0618 0.     0.0563 0.0001 0.0624 0.0001 0.0583 0.0002]
 [0.0037 0.     0.0121 0.0002 0.0137 0.0003 0.0212 0.0005 0.0283 0.0006]
 [0.029  0.     0.0495 0.0001 0.046  0.0003 0.0479 0.0004 0.0419 0.0006]], shape=(3, 10), dtype=float64)


Aunque es posible hacer el siguiente reshape no tiene sentido, porque se pierde la integridad de la información.

Asegúrese que enti3nde la razón.

In [ ]:
print(tf.reshape(t, [3,2,5]))

tf.Tensor(
[[[0.045  0.     0.0618 0.     0.0563]
  [0.0001 0.0624 0.0001 0.0583 0.0002]]

 [[0.0037 0.     0.0121 0.0002 0.0137]
  [0.0003 0.0212 0.0005 0.0283 0.0006]]

 [[0.029  0.     0.0495 0.0001 0.046 ]
  [0.0003 0.0479 0.0004 0.0419 0.0006]]], shape=(3, 2, 5), dtype=float64)


### Definición Conversión de tipos. Cast
---
No definir el tipo de flotante o cantidad de números decimales puede afectar nuestros calculos

In [ ]:
f64_tensor = tf.constant(T[0, :3, 0], dtype = tf.float64)
print(f64_tensor)

f16_tensor = tf.cast(f64_tensor,dtype= tf.float16)
print(f16_tensor)

u8_tensor = tf.cast(f16_tensor, dtype = tf.uint8)
print(u8_tensor)

tf.Tensor([0.04495638 0.06175348 0.05631777], shape=(3,), dtype=float64)
tf.Tensor([0.04495 0.06177 0.0563 ], shape=(3,), dtype=float16)
tf.Tensor([0 0 0], shape=(3,), dtype=uint8)


## Radiofusión (broadcasting)
---
La radiodifusión es un concepto tomado de la función equivalente en NumPy . En resumen, bajo ciertas condiciones, los tensores más pequeños se "estiran" automáticamente para adaptarse a tensores más grandes cuando se ejecutan operaciones combinadas en ellos.

El caso más simple y común es cuando intenta multiplicar o agregar un tensor a un escalar. En ese caso, el escalar se transmite para que tenga la misma forma que el otro argumento.

In [ ]:
x = tf.constant([1, 2 ,3])
y = tf.constant(2)
z = tf.constant([2, 2 ,2])

# el mismo resultado
print(tf.multiply(x,2))
print(x*y)
print(x*z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [ ]:
x = tf.reshape(x, [3,1])
y = tf.range(1,5)
print(x, "\n")
print(y, "\n")

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 



In [ ]:
print(tf.multiply(x,y))

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


Del mismo modo, los ejes con longitud 1 se pueden estirar para que coincidan con los otros argumentos. Ambos argumentos se pueden estirar en el mismo cálculo.

En este caso, una matriz de *3x1* se multiplica por elementos por una matriz de *1x4* para producir una matriz de 3x4. Observe que el 1 inicial es opcional: la forma de y es [4]. En matemáticas esta multiplicación se conoce como **producto externo**.

#### tf.broadcast_to()
---
expande una lista o arreglo al shape desado


In [ ]:
print(tf.broadcast_to([1,2,3], [3,3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


#### tf.convert_to_tensor()
---
convierte listas o array a objetos tensorflow

La mayoría de las operaciones, como *tf.matmul* y *tf.reshape* toman argumentos de la clase *tf.Tensor*. Sin embargo, notará que en el caso anterior, se aceptan objetos de Python con forma de tensores.

La mayoría, pero no todas, las operaciones llaman a *tf.convert_to_tensor* con argumentos no tensoriales. Existe un registro de conversiones, y la mayoría de las clases de objetos como *ndarray* , *TensorShape* , de Python, y *tf.Variable* se convertirán todas automáticamente.

In [ ]:
py_list = [1, 2, 3]
print(type(py_list))
tensor = tf.convert_to_tensor(py_list)
print(type(tensor))

<class 'list'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


### Tensores irregulares (ragged tensors)
---
Un tensor con números variables de elementos a lo largo de algún eje se llama "irregular". Utilice tf.ragged.RaggedTensor para datos irregulares.

Por ejemplo, esto no se puede representar como un tensor regular:

In [1]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

In [4]:
try:
    tensor = tf.constant(ragged_list)
except Exception as e:
     print(f"{type(e).__name__}: {e}")

ValueError: Can't convert non-rectangular Python sequence to Tensor.


En su lugar, cree un tf.RaggedTensor usando ```tf.ragged.constant``` :

In [5]:
ragged_t = tf.ragged.constant(ragged_list)

print(ragged_t.shape)

(4, None)


En este tensor irregular es posible definir que tiene 4 filas pero no es posible la cantidad de columnas dado que son diferente cantidad para cada fila

## Tensores de strings
---
Los tensores irregulares se usan para trabajar con strings

In [15]:
st1 = tf.constant("Este tensor string")
print(st1)

tf.Tensor(b'Este tensor string', shape=(), dtype=string)


In [17]:
st2 = tf.constant(["Este tensor string",
                 "Cadena 2",
                 "Cadena 3",
                 "🥳"])
print(st2)

tf.Tensor([b'Este tensor string' b'Cadena 2' b'Cadena 3' b'\xf0\x9f\xa5\xb3'], shape=(4,), dtype=string)


In [18]:
st2[2]

<tf.Tensor: shape=(), dtype=string, numpy=b'Cadena 3'>

El prefijo b indica que el tipo *(dtype)*  tf.string no es unicode.

In [19]:
print(tf.strings.split(st2))

<tf.RaggedTensor [[b'Este', b'tensor', b'string'], [b'Cadena', b'2'], [b'Cadena', b'3'], [b'\xf0\x9f\xa5\xb3']]>


In [20]:
st_split = tf.strings.split(st)
for i in st_split:
    print(i)

tf.Tensor([b'Este' b'tensor' b'string'], shape=(3,), dtype=string)
tf.Tensor([b'Cadena' b'2'], shape=(2,), dtype=string)
tf.Tensor([b'Cadena' b'3'], shape=(2,), dtype=string)
tf.Tensor([b'\xf0\x9f\xa5\xb3'], shape=(1,), dtype=string)


### string to number

In [23]:
st = tf.constant("1 10 10.4")

print(tf.strings.to_number(tf.strings.split(st, " ")))

tf.Tensor([ 1.  10.  10.4], shape=(3,), dtype=float32)


## Tensores dispersos. SparseTensor
---
Es una funcion que define un tensor por medio de 3 argumentos
> **índices:** índices de los valores que uno quiere definir diferentes a cero

> **values:** son los valores de los datos que uno define para los índices definidos en el primer parámetro

> **dense_shape:** es la forma del tensor los valores que no esten definidos en los parámetros anteriores serán cero.

In [24]:
#  tensor disperso
sparse_tensor = tf.sparse.SparseTensor(indices = [[0,1], [1,2]],
                                       values = [1,2],
                                       dense_shape
                                        =[3,4])
print(sparse_tensor, "\n")

# convierte a tensor denso
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
